name: Open release

on:
  push:
    branches:
      - canary

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare release with Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

        # Tags are fetched for Changeset to distinguish from new ones while running `changeset tag`
      - name: Git fetch tags
        run: git fetch --tags origin

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.10

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm --version && pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          title: Release Payment Template App
          commit: Release Payment Template App
          publish: pnpm github:release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
